DROP DATABASE IF EXISTS VSEC_DB;

CREATE DATABASE VSEC_DB;
USE VSEC_DB;

CREATE TABLE Orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    user_id CHAR(36) NOT NULL,
    status ENUM('CLOSED', 'CANCELED', 'COMPLETE', 'PENDING_PAYMENT', 'SUSPECTED_FRAUD', 'PENDING', 'ON_HOLD', 'PROCESSING', 'PAYMENT_REVIEW') NOT NULL
);

CREATE TABLE IDs (
    user_id CHAR(36) PRIMARY KEY
)