services:
  rust-app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/vsec
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vsec
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d vsec"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: